name: smart-novel-ios
configs:
  dev-debug: debug
  dev-release: release
options:
  deploymentTarget:
    iOS: 13.0
fileGroups:
targets:
  smart-novel-ios:
    type: application
    platform: iOS
    sources: [smart-novel-ios]
    settings:
      configs:
        dev-debug:
          PROVISIONING_PROFILE_SPECIFIER: smartnovel.ios.dev.develop
          CURRENT_PROJECT_VERSION: 1
          PRODUCT_BUNDLE_IDENTIFIER: smart-novel-ios
          CODE_SIGN_STYLE: Manual
          DEVELOPMENT_TEAM: SKD58BVR64
        dev-release:
          PROVISIONING_PROFILE_SPECIFIER: smartnovel.ios.dev.adhoc
          CURRENT_PROJECT_VERSION: 1
          PRODUCT_BUNDLE_IDENTIFIER: smart-novel-ios
          CODE_SIGN_STYLE: Manual
          DEVELOPMENT_TEAM: SKD58BVR64
    dependencies:
    - target: DataStore
    - target: Domain
    - target: Presentation
    info:
        path: smart-novel-ios/Generated/Info.plist
        properties:
            CFBundleDisplayName: SmartNovel
            CFBundleShortVersionString: "1.0.0"
            CFBundleVersion: "4"
            UILaunchStoryboardName: LaunchScreen
            UIRequiredDeviceCapabilities: [armv7]
            LSApplicationQueriesSchemes: ["https", "http"]
            UIRequiresFullScreen: YES
  DataStore:
    type: framework
    platform: iOS
    sources: [DataStore]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: smart-novel-ios.DataStore
      CODE_SIGN_STYLE: Automatic
    dependencies:
      - carthage: RxSwift
      - carthage: RxRelay
      - carthage: RxCocoa
      - carthage: APIKit
  Presentation:
    type: framework
    platform: iOS
    sources: [Presentation]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: smart-novel-ios.Presentation
      CODE_SIGN_STYLE: Automatic
    dependencies:
      - target: Domain
      - carthage: RxSwift
      - carthage: RxRelay
      - carthage: RxCocoa
      - carthage: RxWebKit
      - carthage: Action
      - carthage: Unio
      - carthage: Reusable
      - carthage: TagListView
  Domain:
    type: framework
    platform: iOS
    sources: [Domain]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: smart-novel-ios.Domain
      CODE_SIGN_STYLE: Automatic
    dependencies:
      - target: DataStore
      - carthage: RxSwift
      - carthage: RxRelay
      - carthage: RxCocoa

# スキーム
schemeTemplates:
  SmartNovelScheme:
    build:
      targets:
        smart-novel-ios: all
    run:
      config: ${debugConfig}
    test:
      config: ${debugConfig}
      gatherCoverageData: true
    profile:
      config: ${releaseConfig}
    analyze:
      config: ${debugConfig}
    archive:
      config: ${releaseConfig}
    dev:
      templates: [SmartNovelScheme]
      templateAttributes:
        debugConfig: dev-debug
        releaseConfig: dev-release